### ISSUE TITLE
数据集当中提到的丰富的人物属性（如性别、服装、年龄），在数据集中有标注出来吗？

### ISSUE THREAD

**Issue by wang68815** [GREW-Benchmark/GREW-Benchmark#1]

**Comment by GREW-Benchmark** [comment]
Please give me your email！ I will send the human attributes to you！

**Comment by wang68815** [comment]
好的，我已收到你的邮件[自动回复]

**Comment by wang68815** [comment]
Dear researchers,
Thank you very much! My Email address is
***@***.***







------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年12月22日(星期三) 上午10:51
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [GREW-Benchmark/GREW-Benchmark] 数据集当中提到的丰富的人物属性（如性别、服装、年龄），在数据集中有标注出来吗？ (Issue #1)





 
Please give me your email！ I will send the human attributes to you！
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by GREW-Benchmark** [comment]
I can not see your email. You can send email to xianda_guo@163.com.

**Comment by wang68815** [comment]
好的，我已收到你的邮件[自动回复]
