### ISSUE TITLE
How can I determine the subject of probe?

### ISSUE THREAD

**Issue by timelessnaive** [GREW-Benchmark/GREW-Benchmark#2]
I can not find the subject like "0001" in probe dataset. So how can I get the pair of gallery and probe?

**Comment by NitishJaiswal** [comment]
Gallery and probe are part of test dataset. I believe authors do not provide info of probe subject IDs because they will be running a [GREW - Challenge](https://www.grew-benchmark.org/challenge.html) and thus, test data is not public

**Comment by puyiwen** [comment]
> Gallery and probe are part of test dataset. I believe authors do not provide info of probe subject IDs because they will be running a [GREW - Challenge](https://www.grew-benchmark.org/challenge.html) and thus, test data is not public

Hi, what do you mean " test data is not public"? I find the GREW-Challenge shows "Coming soon", how can I use the test dataset of GREW? Does GREW currently only support training data? Can you help me answer these questions? Thank you very much!!
