### ISSUE TITLE
 Excuse me, your paper "Gait Recognition in the Wild: A Benchmark" is wonderful. But could you please answer a question?

### ISSUE THREAD

**Issue by zhang123-sys** [GREW-Benchmark/GREW-Benchmark#7]
Can "in the Wild" be translated to "在野外" or "在室外" (outdoors) in Chinese?

**Comment by zhang123-sys** [comment]
Thank you.

**Comment by GREW-Benchmark** [comment]
Thank you for your attention to GREW。  "in the Wild" can be translated to “非受控场景” in Chinese
